name: auto_update_readme
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  html: ^0.15.1
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.0
