name: Latest blog post workflow
on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.tech-andgar.me/index.xml"
